name: IN THIS LIFE
favicon: null
layout_spectrum: 0.10571
typography_spectrum: 0.6158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#797979'
    - '#9991a8'
    - '#b6b6b6'
    - '#e7e5d4'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
